config/routes.rb
Rails.application.routes.draw do
  root to: "angular#front_end"

  match '/auth/:provider/callback', :to => 'sessions#create', via: [:get, :post]
  match '/auth/failure', to: redirect('/'), via: :get

  get 'sign_out', to: "sessions#destroy"
  get 'create_account', to: "sessions#new"

  get 'public_rhymes', to: "rhymes#public_index"
  get 'public_rhyme_show/:id', to: "rhymes#public_show"
  resources :users do
    resources :rhymes, except: [:index, :edit]
    get '/rhymes', to: "users#rhymes"
  end

  namespace :api do
    get 'rhymes/:word', to: 'words#rhymes'
    get 'synonyms/:word', to: 'words#synonyms'
  end

end

app/views/layouts/navigations/_authenticated_nav.html.erb
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Account <span class="caret"></span></a>
  <ul class="dropdown-menu" role="menu">
    <li><%= link_to 'Settings', user_path(current_user) %></li>
    <li><%= link_to "My Rhymes", "/#/my-rhymes" %></li>
    <li class="divider"></li>
    <li><%= link_to "Sign Out", sign_out_path %></li>
  </ul>
</li>

app/views/layouts/navigations/_base_nav.html.erb
<nav class="navbar navbar-default rhyme-ninja-nav">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/#/">
        <%= image_tag('ninja_icon.png', class: 'nav-icon') %>
        <span>RhymeNinja</span>
      </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <public-search></public-search>
        </li>

        <%= render partial: "layouts/navigations/#{session_type}_nav" %>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/navigations/_unauthenticated_nav.html.erb
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Sign In<span class="caret"></span></a>
  <ul class="dropdown-menu" role="menu">
    <li class="nav-provider-sign-in">
      <%= image_tag('instagram_icon.png') %>
      <%= link_to "Instagram", "/auth/instagram" %>
    </li>
    <li class="nav-provider-sign-in">
      <%= image_tag('facebook_icon.png') %>
      <%= link_to "Facebook", "/auth/facebook" %>
    </li>
    <li class="nav-provider-sign-in">
      <%= image_tag('twitter_icon.png') %>
      <%= link_to 'Twitter', "auth/twitter" %>
    </li>
    <li class="nav-provider-sign-in">
      <%= image_tag('google_icon.png') %>
      <%= link_to "Google", "/auth/google_oauth2" %>
    </li>
    <li class="divider"></li>
    <li class="password-sign-in">
      <div class="form-toggle">
        <%= image_tag('ninja_icon.png', class: 'sign-in-ninja-icon') %>
          Email
      </div>
      <%= render partial: "shared/forms/password_sign_in" %>
    </li>
  </ul>
</li>
<li>
  <%= link_to "Create Account", create_account_path %>
</li>


<% content_for :javascript do %>
  <script type="text/javascript">
    $(function(){
      $('li.password-sign-in > .form-toggle').click(function(e){
        e.stopPropagation();
        $('form.password-sign-in-form').toggle();
      });
    });
  </script>
<% end %>